### ISSUE TITLE
Abgabe nicht möglich

### ISSUE THREAD

**Issue by alexander-leonhardsberger** [rstropek-teaching/address-book-quiz-4ahif-alexleo2000#1]
Ich war nicht im Stande die Übung rechtzeitig abzugeben, da mein Windows eine Fehlerhafte Installation durchgeführt hatte und dies ständig zu einem Bluescreen führt. Ich werde die Übung so bald wie möglich nachreichen.

**Comment by rstropek** [comment]
Ok, Danke für die Info. Bitte ein GitHub Issue eintragen wenn die Übung fertig ist. Dann weiß ich, wann ich drauf schauen soll.

lg,
Rainer Stropek
